- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t jenkins-sonar .
      args:
        chdir: /var/lib/jenkins/workspace/jenkins-sonar



    - name: tag image
      command: docker tag jenkins-sonar:latest alinabagwan12345/jenkins-sonar:latest 

    - name: Log in to Docker Hub
       docker_login:
          username: alinabagwan12345
          password: Wahid@12345

    - name: Push image
      command: docker push alinabagwan12345/jenkins-sonar:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 alinabagwan12345/jenkins-sonar:latest
